version: '3'

x-defaults: &defaults
    environment:
        - AWS_ACCESS_KEY_ID=local
        - AWS_SECRET_ACCESS_KEY=local
        - AWS_DEFAULT_REGION=us-west-2
        - DYNAMODB_TABLE_NAME=migrations

services:
    migrate:
        <<: *defaults
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - dynamodb
        volumes:
            - ./src:/src
            - ./examples:/examples

    dynamodb:
        <<: *defaults
        image: amazon/dynamodb-local
        ports:
            - 8000:8000
